### ISSUE TITLE
Maybe remove the ES6 classes

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/mc-react-solves-what-now#3]
If the goal is to get them to understand the idea of storing state in JavaScript and re-rendering their app every time this state changes, maybe the classes will distract them from that.

This is as simple as I could make the solution using just functions:

```js
function createElement({ tagName, text, onClick }) {
  const element = document.createElement(tagName);
  element.textContent = text;
  element.onclick = onClick;
  return element;
}

let state = { count: 0 };

function Button() {
  return createElement({
    tagName: "button",
    text: `Count ${state.count}`,
    onClick: () => setState({ count: state.count + 1 })
  });
}

function renderApp(Child, root) {
  root.innerHTML = "";
  return root.appendChild(Child());
}

function setState(newState) {
  Object.assign(state, newState);
  renderApp(Button, document.getElementById("root"));
}

renderApp(Button, document.getElementById("root"));
```

[Working Repl](https://repl.it/@oliverjam/mini-react)

It also sort of introduces them to the concept of React Components being functions that get re-called when they re-render.

I'm not sure exactly what parts we'd have them write—maybe `renderApp` and `setState`? That's all you need to get the learning outcome of re-rendering the app based on state updates.

**Comment by oliverjam** [comment]
@sofiapoh would be okay if I did a PR to make the challenge more like the above?

**Comment by sofiapoh** [comment]
@oliverjam Go for it!
